### ISSUE TITLE
Having a property called 'body' breaks parser

### ISSUE THREAD

**Issue by pguillebert** [raml2html/raml2obj#14]
Hi

I'm using raml2html@4.0.0-beta5 and raml2obj@4.0.0-beta6. We're modeling our API using RAML and some JSON object (RAML type) has a `body` field storing the body of a message (along with title, date, etc) 

Error is: 
```
TypeError: Cannot create property 'key' on string 'body'
    at Object.keys.map (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:28:18)
    at Array.map (native)
    at _objectToArray (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:27:27)
    at Object.keys.forEach (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:116:20)
    at Array.forEach (native)
    at _recursiveObjectToArray (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:113:22)
    at Object.keys.forEach (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:125:7)
    at Array.forEach (native)
    at _recursiveObjectToArray (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:113:22)
    at Object.keys.forEach (/usr/local/lib/node_modules/raml2html/node_modules/raml2obj/index.js:125:7)
```

Is it a spec issue or a parser issue ? Thank you.

**Comment by pguillebert** [comment]
Oh, and this is a RAML 1.0 spec.

**Comment by sichvoge** [comment]
Can you post your RAML file please.

**Comment by pguillebert** [comment]
```
#%RAML 1.0
title: Stripped example
version: 1
baseUri: http://example.com/{version}

types:
  Comment:
    type: object
    properties:
      author:
        type: string
        required: true
      body:
        type: string
        required: true
      date:
        type: integer
        required: true
      editAuthor:
        type: string
        required: false
      edited:
        type: integer
        required: false

  Conversation:
    type: object
    properties:
      comments:
        type: Comment[]
        minItems: 1
      attachedTo:
        type: string
        required: true

##########################
# Conversations
##########################

/conversations/{conversationId}:
  post:
    description: |
      Add one comment to the conversation identified by `conversationId`.
    body:
      application/json:
        type: Comment
    responses:
      200:
        body:
          application/json:
            type: Conversation
```

**Comment by kevinrenskers** [comment]
Thanks, I see the problem and will fix it tomorrow.

**Comment by kevinrenskers** [comment]
Fixed, released beta 7. Thanks for your bug report!
