### ISSUE TITLE
Mac Osx Node 14: Invalid or unexpected token

### ISSUE THREAD

**Issue by aljones15** [raml2html/raml2obj#72]
```js
/node_modules/raml2html/node_modules/raml2obj/index.js:1
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:101:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at wrapSafe (internal/modules/cjs/loader.js:967:15)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
npm ERR! Test failed.  See above for more details.
```

**Comment by kevinrenskers** [comment]
Can you explain what you were doing to get this error? This is not enough info to go off. I am able to run raml2html just fine on macOS using Node 15 for example.

**Comment by aljones15** [comment]
> Can you explain what you were doing to get this error? This is not enough info to go off. I am able to run raml2html just fine on macOS using Node 15 for example.

using a documentation library that uses `raml2html`:

https://github.com/raml2html/raml2html/blob/449f0528c9f0100ad53c6f5b2fc0fe7ccff5b1ae/index.js#L3

https://github.com/digitalbazaar/bedrock-docs/blob/72678bba8fc6d3b67b7676703f07e3c7866bb8e7/lib/services.docs.js#L13

I just ran into this issue again today. Several sources claim the problem is `index.js` is not `UTF-8` encoded.

**Comment by kevinrenskers** [comment]
The only place where `#!/usr/bin/env node` is included, is in the command line application, inside [bin/raml2html](https://github.com/raml2html/raml2html/blob/master/bin/raml2html). So it kinda looks like the wrong file is getting required?

**Comment by aljones15** [comment]
the one that is throwing (according to the stack trace) is the 

https://github.com/raml2html/raml2obj/blob/9a0a4e794472de9b9ec9a70b974138341b93bd9b/index.js#L1

in your library. which is required by `raml2html`'s index.js.

**Comment by kevinrenskers** [comment]
Ah, good find. Yeah I am not sure why that one has that header.. it's not a CLI at all.

**Comment by kevinrenskers** [comment]
I've published raml2obj 6.8.1, hopefully that fixes things.
